# Generated by Django 4.0.4 on 2022-04-16 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Start date')),
                ('date_end', models.DateField(verbose_name='End date')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('text_field', 'Ответ текстом'), ('radio', 'Ответ с выбором одного варианта'), ('check_boxes', 'Ответ с выбором нескольких вариантов')], max_length=20, verbose_name='Тип вопроса')),
                ('questionnaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.questionnaire')),
            ],
        ),
    ]
